app.security.enabled=true
app.refresh-token.store=memory
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
logging.file.name=
