spring.application.name=cinetime

server.port=8081

server.error.include-binding-errors=always
server.error.include-message=always
server.error.include-stacktrace=never

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cinetime_db
spring.datasource.username=db_user
spring.datasource.password=password

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#logging
logging.file.name= log/cinetime.log
logging.pattern.file= "%d %-5level [%thread] %logger:%msg%n"
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=INFO
logging.level.com.tpe.cinetime=INFO

#keys
jwt.secret=PycPZyaO4h+5btTyCZZcc9AR7Ghq3KMjI1o6BJS+QFdq/VrKBdrHZvPlPVheEI+wJD5+hYBw0AX9ELVygEOwfg==
jwt.expiration=86400000

#admin credentials
app.admin.email=admin@cinetime.com
app.admin.password=Admin123

